// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EFConsole.Model
{
    [Table("CUSTOMERS")]
    [Index(nameof(Namesurname), nameof(Id), nameof(Gender), nameof(Birthdate), nameof(City), nameof(Town), nameof(Telnr), nameof(Name), nameof(Surname), Name = "IX1")]
    public partial class Customer
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("NAMESURNAME")]
        [StringLength(150)]
        public string Namesurname { get; set; }
        [Column("GENDER")]
        [StringLength(1)]
        public string Gender { get; set; }
        [Column("BIRTHDATE", TypeName = "date")]
        public DateTime? Birthdate { get; set; }
        [Column("CITY")]
        [StringLength(100)]
        public string City { get; set; }
        [Column("TOWN")]
        [StringLength(100)]
        public string Town { get; set; }
        [Column("TELNR")]
        [StringLength(50)]
        public string Telnr { get; set; }
        [Column("NAME_")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("SURNAME")]
        [StringLength(50)]
        public string Surname { get; set; }
        [Column("TCNO")]
        [StringLength(20)]
        public string Tcno { get; set; }
    }
}